### ISSUE TITLE
Include googlemaps in article.ejs

### ISSUE THREAD

**Issue by ghost** [the-simian/hexo-tag-googlemaps#15]
How to include googlemaps in `article.ejs`? I would love to have this plugin in my themes, not in .md files.

Meaning, use it like `<%- post.googlemaps %>` for example. Possible to do?

Also for the three markers to write them like...

`<%- post.title %>, <%- post.latitude %>, <%- post.longitude %>` 

Would that be possible somehow too?

**Comment by the-simian** [comment]
Can you post an example of what you're trying to do, maybe I can help. Is the idea that it would be the same google map for every post?

**Comment by rabas007** [comment]
@the-simian - thank you for your quick reply.

To explain... I have a restaurants review site, and each blogpost is a different restaurant. I have template variables defined in my `post.ejs` file that correspond to my `md` files. For example, `post.restaurantname` and `post.foodtype`, etc. in my `post.ejs`. Then in my `.md` files, I have `post.restaurantname: pizzeria` and `post.foodtype: italian`. So now for each `post`, meaning each `restaurant`, I want to show the address on googlemaps. I am trying to figure out how to do that with your plugin.
