### ISSUE TITLE
The plugin is worth publishing

### ISSUE THREAD

**Issue by Hunter-Github** [the-simian/hexo-tag-googlemaps#4]
The plugin is definitely worth publishing to Hexo's official list. Thank you, it's a great helper.

Reference: http://hexo.io/docs/plugins.html#Publishing

**Comment by the-simian** [comment]
hey thanks, I forgot they moved the plugin list!

**Comment by the-simian** [comment]
references https://github.com/hexojs/site/pull/56/files   tommy351/hexojs/site#56

**Comment by the-simian** [comment]
@Hunter-Github  Thanks again, its published now!
