### ISSUE TITLE
Marker message on click not appearing

### ISSUE THREAD

**Issue by DrummerHead** [the-simian/hexo-tag-googlemaps#8]
Hi Jesse! Thanks for the plugin :) 

Currently the icon message is not displaying, you can verify this at http://okcjs.com/2015/07/21/2015-7-21-webgl-the-hard-way/#more

I'm going to be looking at this and trying to fix it, but I'll also let you know, perhaps you're more in tune with google maps' updates and know how to fix this easily.

Cheers!

**Comment by the-simian** [comment]
Hey for whatever reason I am just now seeing this issue submission, but I will also say that the message was actually displaying for me.

**Comment by DrummerHead** [comment]
Hi @the-simian a screenshot would be hard because it would be a screenshot of the absence of a feature. If you head over to http://okcjs.com/2015/07/21/2015-7-21-webgl-the-hard-way/#more and look at the map on chrome, firefox or safari and click on the icon, you would see that there is no tooltip showing the title "Prototek OKC" (although it does appear on hover as a regular title attribute would)

I've taken the liberty of making the title appear, you can see it at this pull request: https://github.com/the-simian/hexo-tag-googlemaps/pull/9

Cheers!

**Comment by the-simian** [comment]
I merged this right in, I appreciate the update very  much!
